openapi: 3.0.0
info:
  title: Online School API
  version: 1.0.0
paths:
  /persons:
    post:
      summary: Create person
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PersonCreate'
      responses:
        '201':
          description: Created
    get:
      summary: Retrieve all persons
      responses:
        '200':
          description: List of persons
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Person'
        '204':
          description: No persons found
  /persons/{id}:
    get:
      summary: Retrieve single person
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Person details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Person'
        '404':
          description: Not found
        '204':
           description: No content
    put:
      summary: Update person
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PersonUpdate'
      responses:
        '204':
          description: Updated
    delete:
      summary: Delete person
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: Deleted

  /courses:
    post:
      summary: Create course
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CourseCreate'
      responses:
        '201':
          description: Created
    get:
      summary: Retrieve all courses
      responses:
        '200':
          description: List of courses
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Course'
        '204':
          description: No courses found
  /courses/{id}:
    get:
      summary: Retrieve single course
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Course details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Course'
        '404':
          description: Not found
        '204':
          description: No content
    put:
      summary: Update course
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CourseUpdate'
      responses:
        '204':
          description: Updated
    delete:
      summary: Delete course
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: Deleted

  /modules:
    post:
      summary: Create module
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ModuleCreate'
      responses:
        '201':
          description: Created
    get:
      summary: Retrieve all modules
      responses:
        '200':
          description: List of modules
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Module'
        '204':
          description: No modules found
  /modules/{id}:
    get:
      summary: Retrieve single module
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Module details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Module'
        '404':
          description: Not found
        '204':
          description: No content
    put:
      summary: Update module
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ModuleUpdate'
      responses:
        '204':
          description: Updated
    delete:
      summary: Delete module
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: Deleted

components:
  schemas:
    PersonCreate:
      type: object
      properties:
        first_name:
          type: string
        last_name:
          type: string
        borned_at:
          type: string
          format: date-time
        phone_number:
          type: string
        email:
          type: string
        password:
          type: string
    Person:
      type: object
      properties:
        id:
          type: integer
          format: int64
        role:
          type: string
        first_name:
          type: string
        last_name:
          type: string
        borned_at:
          type: string
          format: date-time
        phone_number:
          type: string
        email:
          type: string
        status:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
    PersonUpdate:
      type: object
      properties:
        role:
          type: string
        first_name:
          type: string
        last_name:
          type: string
        borned_at:
          type: string
          format: date-time
        phone_number:
          type: string
        email:
          type: string
        password:
          type: string
        status:
          type: string

    CourseCreate:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
    Course:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        description:
          type: string
        modules_number:
          type: integer
        status:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
    CourseUpdate:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        status:
          type: string

    ModuleCreate:
      type: object
      properties:
        name:
          type: string
        course:
          type: string
        description:
          type: string
    Module:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        course:
          type: string
        description:
          type: string
        lessons_number:
          type: integer
        status:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
    ModuleUpdate:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        status:
          type: string
